[package]
name = "futures-enum"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.1.9"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "#[derive(Future, Stream, Sink, AsyncRead, AsyncWrite)] for enums."
repository = "https://github.com/taiki-e/futures-enum"
documentation = "https://docs.rs/futures-enum/"
readme = "README.md"
keywords = ["futures", "async", "future", "derive", "enum"]
categories = ["asynchronous", "rust-patterns"]

[lib]
proc-macro = true

[features]
default = []
# TODO
# compat = []
# io-compat = []

[dependencies]
derive_utils = "0.8.0"
find-crate = "0.4.0"
proc-macro2 = "0.4.13"
quote = "0.6.8"
syn = { version = "0.15.29", features = ["full"] }

[dev-dependencies]
futureio = { version = "=0.3.0-alpha.17", package = "futures-io-preview" }
futures-sink-preview = { version = "=0.3.0-alpha.17", package = "futures-sink-preview" }
futures-core-preview = { version = "=0.3.0-alpha.17" }
futures-preview = { version = "=0.3.0-alpha.17" }
