[package]
name = "futures-enum"
version = "0.1.11"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/futures-enum"
documentation = "https://docs.rs/futures-enum/"
keywords = ["futures", "async", "future", "derive", "enum"]
categories = ["asynchronous", "rust-patterns"]
readme = "README.md"
description = """
#[derive(Future, Stream, Sink, AsyncRead, AsyncWrite, AsyncSeek, AsyncBufRead)] for enums.
"""

[lib]
proc-macro = true

[features]
default = ["renamed"]
# Enable to allow using this crate as a renamed dependency
renamed = ["find-crate"]

[dependencies]
derive_utils = "0.9.1"
find-crate = { version = "0.5", optional = true }
quote = "1.0"
syn = "1.0"

[dev-dependencies]
futureio = { version = "0.3.0-alpha.19", package = "futures-io-preview" }
futures-sink-preview = { version = "0.3.0-alpha.19", package = "futures-sink-preview" }
futures-core-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
futures-preview = "0.3.0-alpha.19"
