parameters:
  vmImage: ubuntu-16.04
  cmd: test

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
    - template: azure-install-rust.yml
      parameters:
        toolchain: ${{ parameters.toolchain }}

    - ${{ if not(eq(parameters.cmd, 'test')) }}:
      - script: |
          cargo ${{ parameters.cmd }} --no-default-features
          cargo ${{ parameters.cmd }}
        displayName: cargo ${{ parameters.cmd }}

    - ${{ if eq(parameters.cmd, 'test') }}:
      - script: |
          cargo ${{ parameters.cmd }} --tests --no-default-features
          cargo ${{ parameters.cmd }} --tests
        displayName: cargo ${{ parameters.cmd }} --tests

    - ${{ if eq(parameters.toolchain, 'nightly') }}:
      - script: |
          cargo ${{ parameters.cmd }}
        displayName: cargo ${{ parameters.cmd }}

      # Refs: https://github.com/rust-lang/cargo/issues/5657
      - script: |
          cargo update -Zminimal-versions
          cargo check
        displayName: cargo check -Zminimal-versions
